"""
Graphify

Phase 3

Stage P3.5

Engineering Plan

Represents an executable engineering
sprint generated by the Executive.

Author:
Graphify Core
"""


class EngineeringPlan:

    VERSION = "P3.5"

    def __init__(

        self,

        strategy,

        objective,

        priority,

        tasks,

        assigned_roles,

    ):

        self.strategy = strategy

        self.objective = objective

        self.priority = priority

        self.tasks = tasks

        self.assigned_roles = assigned_roles

    # --------------------------------------------------

    def summary(self):

        return {

            "strategy": self.strategy,

            "objective": self.objective,

            "priority": self.priority,

            "tasks": len(self.tasks),

            "assigned_roles": self.assigned_roles,

            "version": self.VERSION,

        }

    # --------------------------------------------------

    def details(self):

        return {

            "strategy": self.strategy,

            "objective": self.objective,

            "priority": self.priority,

            "tasks": self.tasks,

            "assigned_roles": self.assigned_roles,

            "version": self.VERSION,

        }