"""
Graphify

Knowledge Graph

Legacy Builder

Preserves the original functional Knowledge Graph API
during the migration to the object-oriented Knowledge
Graph package.

This module exists for backward compatibility and
will be retired once all callers migrate to
KnowledgeGraphBuilder.

Author:
Graphify Core
"""


def build_knowledge_graph(symbol_index):
    """
    Build a simple symbol dependency graph.

    Parameters
    ----------
    symbol_index : dict
        Symbol index generated by Graphify.

    Returns
    -------
    dict
        Symbol dependency graph.
    """

    graph = {}

    for symbol, data in symbol_index.items():

        graph[symbol] = []

        for usage in data["used_by"]:

            caller = usage["caller"]

            # Ignore recursive self-calls
            if caller == symbol:
                continue

            graph[symbol].append(caller)

    return graph